background {
    monitor =
    path = screenshot
    blur_passes = 2
}

auth {
    fingerprint {
        enabled = true
    }
}

animations {
    enabled = false
}

input-field {
    monitor =
    halign = center
    valign = center
    font_family = "JetBrainsMono Nerd Font"
    capslock_color = rgb(255, 0, 0)
}
