-- ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
-- ┃                     Monitor Configuration                     ┃
-- ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
-- Generated by nwg-displays on 2025-12-06 at 00:16:07. Do not edit manually.

hl.monitor({
    output   = "eDP-1",
    mode     = "2880x1920@120.0",
    position = "0x0",
    scale    = 1.5,
})
