# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Variables Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

general {
    gaps_in = 0
    gaps_out = 0
    layout = dwindle # master|dwindle

    col.active_border = rgb(98971a)
}

# this is tabs config
# but not like i3, way worse since you have to manually add all windows to the group
# for my use case, full screen of a particular window is better/enough
group {
    auto_group = false
	groupbar {
        enabled = true
	}
}

misc {
    font_family = "JetBrainsMono Nerd Font Mono"
    splash_font_family = "JetBrainsMono Nerd Font Mono"
    disable_hyprland_logo = true
    focus_on_activate = true
    vrr = 2
}

render {
   direct_scanout = 2
}

# See https://wiki.hyprland.org/0.45.0/Configuring/Dwindle-Layout/ for more
dwindle {
    force_split = 2
    preserve_split = true
}
